### ISSUE TITLE
works from command line, but issue when running from hudson

### ISSUE THREAD

**Issue by klm1** [klm1/kiln-local-backup#2]
**Archival post from Google Code**

Posted on Jun 14, 2010 by Massive Ox

Hello. Love your script. Works great.

I know you are not supporting for hudson or anything, I just wondered if you might be able to point me towards solving an error message. I'm not a python programmer.

When using hudson and running the script from shell as:

python "/var/lib/hudson/kiln-local-backup/kiln_local_backup.py" --help

Everything works fine.

When trying to run:

python "/var/lib/hudson/kiln-local-backup/kiln_local_backup.py" /var/lib/hudson/repos

It fails with the error messages listed below. Is is looking for the repo api, ect.? I have already run the script as the hudson user from the command line so this info should be saved. I also tried passing the token and server in --token and --server.

The error is the same for both attempts:
- python /var/lib/hudson/kiln-local-backup/kiln_local_backup.py /var/lib/hudson/repos Traceback (most recent call last): File "/var/lib/hudson/kiln-local-backup/kiln_local_backup.py", line 349, in <module> sys.exit(main()) File "/var/lib/hudson/kiln-local-backup/kiln_local_backup.py", line 272, in main repos = get_repos(options.server, options.token, options.verbose) File "/var/lib/hudson/kiln-local-backup/kiln_local_backup.py", line 114, in get_repos server) File "/var/lib/hudson/kiln-local-backup/kiln_local_backup.py", line 209, in console_encode if sys.stdout.encoding.upper().startswith('UTF'): AttributeError: 'NoneType' object has no attribute 'upper'

**Comment by klm1** [comment]
Posted on Jun 14, 2010 by Massive Ox

I can get it to run from hudson by using the --quiet option. It then runs correctly.

I'd like to solve the issues with

if sys.stdout.encoding.upper().startswith('UTF'): AttributeError: 'NoneType' object has no attribute 'upper'

So I may get a full verbose report in my Hudson console. Any ideas?

Thanks and best regards.

**Comment by klm1** [comment]
Posted on Dec 15, 2010 by Quick Monkey
I see the same issue when running the script from NAnt. I think the underlying problem here is that by default NAnt (and probably Hudson) run programs without a shell.

I modified the script slightly from this:

line 209: if sys.stdout.encoding.upper().startswith('UTF'):

to:

line 209: if sys.stdout.encoding == None: line 210: return message line 211: elif sys.stdout.encoding.upper().startswith('UTF'):

which seems to do the trick.

**Comment by klm1** [comment]
Posted on Dec 20, 2010 by Quick Kangaroo

This is now fixed. In addition to Kenneth’s fix, I also forced the output to 'ASCII' if there is no stdout.encoding, otherwise non-ASCII repository names would still cause a problem.
