### ISSUE TITLE
403 when attempting to backup

### ISSUE THREAD

**Issue by klm1** [klm1/kiln-local-backup#6]
**Archival post from Google Code**

Posted on May 16, 2012 by Happy Bird

**What steps will reproduce the problem?** 1. execute script 2. give api key and server hostname

**What is the expected output?** **What do you see instead?** Expect to get password prompt or to execute backup. Instead I get an exception from urllib2: Getting the list of repositories from SOME_REPO_HERE.kilnhg.com Traceback (most recent call last): File "kiln_local_backup.py", line 382, in <module> sys.exit(main()) File "kiln_local_backup.py", line 294, in main repos = get_repos(options.scheme, options.server, options.token, options.verbose) File "kiln_local_backup.py", line 134, in get_repos data = json.load(urllib2.urlopen(url)) File "c:\python27\lib\urllib2.py", line 126, in urlopen return _opener.open(url, data, timeout) File "c:\python27\lib\urllib2.py", line 406, in open response = meth(req, response) File "c:\python27\lib\urllib2.py", line 519, in http_response 'http', request, response, code, msg, hdrs) File "c:\python27\lib\urllib2.py", line 444, in error return self._call_chain(_args) File "c:\python27\lib\urllib2.py", line 378, in _call_chain result = func(_args) File "c:\python27\lib\urllib2.py", line 527, in http_error_default raise HTTPError(req.get_full_url(), code, msg, hdrs, fp) urllib2.HTTPError: HTTP Error 403: Forbidden

**What version of the product are you using? On what operating system?** Latest on WinXP python 2.7

**Please provide any additional information below.** None

**Comment by klm1** [comment]
Posted on May 16, 2012 by Happy Bird

Nevermind... I had the wrong api key.

**Comment by klm1** [comment]
Posted on Jul 30, 2012 by Happy Bird

Closed -- owner indicated no longer a problem.
